# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/koragg/Downloads/Projects/open source/quick-lint-js"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/koragg/Downloads/Projects/open source/quick-lint-js"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"build-tools\" \"simdjson_Development\" \"vscode-node\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/koragg/Downloads/Projects/open source/quick-lint-js/CMakeFiles" "/Users/koragg/Downloads/Projects/open source/quick-lint-js//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/koragg/Downloads/Projects/open source/quick-lint-js/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named boost_json

# Build rule for target.
boost_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_json
.PHONY : boost_json

# fast build rule for target.
boost_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_json.dir/build.make CMakeFiles/boost_json.dir/build
.PHONY : boost_json/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named quick-lint-js-analyze-trace

# Build rule for target.
quick-lint-js-analyze-trace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-analyze-trace
.PHONY : quick-lint-js-analyze-trace

# fast build rule for target.
quick-lint-js-analyze-trace/fast:
	$(MAKE) $(MAKESILENT) -f tools/CMakeFiles/quick-lint-js-analyze-trace.dir/build.make tools/CMakeFiles/quick-lint-js-analyze-trace.dir/build
.PHONY : quick-lint-js-analyze-trace/fast

#=============================================================================
# Target rules for targets named quick-lint-js-generate-lex-keyword

# Build rule for target.
quick-lint-js-generate-lex-keyword: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-generate-lex-keyword
.PHONY : quick-lint-js-generate-lex-keyword

# fast build rule for target.
quick-lint-js-generate-lex-keyword/fast:
	$(MAKE) $(MAKESILENT) -f tools/CMakeFiles/quick-lint-js-generate-lex-keyword.dir/build.make tools/CMakeFiles/quick-lint-js-generate-lex-keyword.dir/build
.PHONY : quick-lint-js-generate-lex-keyword/fast

#=============================================================================
# Target rules for targets named quick-lint-js-build-tools

# Build rule for target.
quick-lint-js-build-tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-build-tools
.PHONY : quick-lint-js-build-tools

# fast build rule for target.
quick-lint-js-build-tools/fast:
	$(MAKE) $(MAKESILENT) -f tools/CMakeFiles/quick-lint-js-build-tools.dir/build.make tools/CMakeFiles/quick-lint-js-build-tools.dir/build
.PHONY : quick-lint-js-build-tools/fast

#=============================================================================
# Target rules for targets named quick-lint-js-test-typescript

# Build rule for target.
quick-lint-js-test-typescript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-test-typescript
.PHONY : quick-lint-js-test-typescript

# fast build rule for target.
quick-lint-js-test-typescript/fast:
	$(MAKE) $(MAKESILENT) -f tools/test-typescript/CMakeFiles/quick-lint-js-test-typescript.dir/build.make tools/test-typescript/CMakeFiles/quick-lint-js-test-typescript.dir/build
.PHONY : quick-lint-js-test-typescript/fast

#=============================================================================
# Target rules for targets named quick-lint-js-typescript-test-lib

# Build rule for target.
quick-lint-js-typescript-test-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-typescript-test-lib
.PHONY : quick-lint-js-typescript-test-lib

# fast build rule for target.
quick-lint-js-typescript-test-lib/fast:
	$(MAKE) $(MAKESILENT) -f tools/test-typescript/CMakeFiles/quick-lint-js-typescript-test-lib.dir/build.make tools/test-typescript/CMakeFiles/quick-lint-js-typescript-test-lib.dir/build
.PHONY : quick-lint-js-typescript-test-lib/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f vendor/googletest/googlemock/CMakeFiles/gmock.dir/build.make vendor/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f vendor/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make vendor/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f vendor/googletest/googletest/CMakeFiles/gtest.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build.make vendor/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named simdjson

# Build rule for target.
simdjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdjson
.PHONY : simdjson

# fast build rule for target.
simdjson/fast:
	$(MAKE) $(MAKESILENT) -f vendor/simdjson/CMakeFiles/simdjson.dir/build.make vendor/simdjson/CMakeFiles/simdjson.dir/build
.PHONY : simdjson/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-configuration-json

# Build rule for target.
quick-lint-js-fuzz-configuration-json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-configuration-json
.PHONY : quick-lint-js-fuzz-configuration-json

# fast build rule for target.
quick-lint-js-fuzz-configuration-json/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-configuration-json.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-configuration-json.dir/build
.PHONY : quick-lint-js-fuzz-configuration-json/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-lex

# Build rule for target.
quick-lint-js-fuzz-lex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-lex
.PHONY : quick-lint-js-fuzz-lex

# fast build rule for target.
quick-lint-js-fuzz-lex/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-lex.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-lex.dir/build
.PHONY : quick-lint-js-fuzz-lex/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-lsp-server

# Build rule for target.
quick-lint-js-fuzz-lsp-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-lsp-server
.PHONY : quick-lint-js-fuzz-lsp-server

# fast build rule for target.
quick-lint-js-fuzz-lsp-server/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-lsp-server.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-lsp-server.dir/build
.PHONY : quick-lint-js-fuzz-lsp-server/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-lsp-message-parser

# Build rule for target.
quick-lint-js-fuzz-lsp-message-parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-lsp-message-parser
.PHONY : quick-lint-js-fuzz-lsp-message-parser

# fast build rule for target.
quick-lint-js-fuzz-lsp-message-parser/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-lsp-message-parser.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-lsp-message-parser.dir/build
.PHONY : quick-lint-js-fuzz-lsp-message-parser/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-options

# Build rule for target.
quick-lint-js-fuzz-options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-options
.PHONY : quick-lint-js-fuzz-options

# fast build rule for target.
quick-lint-js-fuzz-options/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-options.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-options.dir/build
.PHONY : quick-lint-js-fuzz-options/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-parse

# Build rule for target.
quick-lint-js-fuzz-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-parse
.PHONY : quick-lint-js-fuzz-parse

# fast build rule for target.
quick-lint-js-fuzz-parse/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-parse.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-parse.dir/build
.PHONY : quick-lint-js-fuzz-parse/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-parse-lint

# Build rule for target.
quick-lint-js-fuzz-parse-lint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-parse-lint
.PHONY : quick-lint-js-fuzz-parse-lint

# fast build rule for target.
quick-lint-js-fuzz-parse-lint/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-parse-lint.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-parse-lint.dir/build
.PHONY : quick-lint-js-fuzz-parse-lint/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-utf-8-decode-encode

# Build rule for target.
quick-lint-js-fuzz-utf-8-decode-encode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-utf-8-decode-encode
.PHONY : quick-lint-js-fuzz-utf-8-decode-encode

# fast build rule for target.
quick-lint-js-fuzz-utf-8-decode-encode/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-utf-8-decode-encode.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-utf-8-decode-encode.dir/build
.PHONY : quick-lint-js-fuzz-utf-8-decode-encode/fast

#=============================================================================
# Target rules for targets named quick-lint-js-fuzz-utf-8-lsp

# Build rule for target.
quick-lint-js-fuzz-utf-8-lsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-fuzz-utf-8-lsp
.PHONY : quick-lint-js-fuzz-utf-8-lsp

# fast build rule for target.
quick-lint-js-fuzz-utf-8-lsp/fast:
	$(MAKE) $(MAKESILENT) -f fuzz/CMakeFiles/quick-lint-js-fuzz-utf-8-lsp.dir/build.make fuzz/CMakeFiles/quick-lint-js-fuzz-utf-8-lsp.dir/build
.PHONY : quick-lint-js-fuzz-utf-8-lsp/fast

#=============================================================================
# Target rules for targets named quick-lint-js-vscode-node

# Build rule for target.
quick-lint-js-vscode-node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-vscode-node
.PHONY : quick-lint-js-vscode-node

# fast build rule for target.
quick-lint-js-vscode-node/fast:
	$(MAKE) $(MAKESILENT) -f plugin/vscode/CMakeFiles/quick-lint-js-vscode-node.dir/build.make plugin/vscode/CMakeFiles/quick-lint-js-vscode-node.dir/build
.PHONY : quick-lint-js-vscode-node/fast

#=============================================================================
# Target rules for targets named quick-lint-js-vscode-node-licenses

# Build rule for target.
quick-lint-js-vscode-node-licenses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-vscode-node-licenses
.PHONY : quick-lint-js-vscode-node-licenses

# fast build rule for target.
quick-lint-js-vscode-node-licenses/fast:
	$(MAKE) $(MAKESILENT) -f plugin/vscode/CMakeFiles/quick-lint-js-vscode-node-licenses.dir/build.make plugin/vscode/CMakeFiles/quick-lint-js-vscode-node-licenses.dir/build
.PHONY : quick-lint-js-vscode-node-licenses/fast

#=============================================================================
# Target rules for targets named quick-lint-js

# Build rule for target.
quick-lint-js: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js
.PHONY : quick-lint-js

# fast build rule for target.
quick-lint-js/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js.dir/build.make src/CMakeFiles/quick-lint-js.dir/build
.PHONY : quick-lint-js/fast

#=============================================================================
# Target rules for targets named quick-lint-js-tool-lib

# Build rule for target.
quick-lint-js-tool-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-tool-lib
.PHONY : quick-lint-js-tool-lib

# fast build rule for target.
quick-lint-js-tool-lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js-tool-lib.dir/build.make src/CMakeFiles/quick-lint-js-tool-lib.dir/build
.PHONY : quick-lint-js-tool-lib/fast

#=============================================================================
# Target rules for targets named quick-lint-js-lib

# Build rule for target.
quick-lint-js-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-lib
.PHONY : quick-lint-js-lib

# fast build rule for target.
quick-lint-js-lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js-lib.dir/build.make src/CMakeFiles/quick-lint-js-lib.dir/build
.PHONY : quick-lint-js-lib/fast

#=============================================================================
# Target rules for targets named quick-lint-js-lib-debug

# Build rule for target.
quick-lint-js-lib-debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-lib-debug
.PHONY : quick-lint-js-lib-debug

# fast build rule for target.
quick-lint-js-lib-debug/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js-lib-debug.dir/build.make src/CMakeFiles/quick-lint-js-lib-debug.dir/build
.PHONY : quick-lint-js-lib-debug/fast

#=============================================================================
# Target rules for targets named quick-lint-js-licenses

# Build rule for target.
quick-lint-js-licenses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-licenses
.PHONY : quick-lint-js-licenses

# fast build rule for target.
quick-lint-js-licenses/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js-licenses.dir/build.make src/CMakeFiles/quick-lint-js-licenses.dir/build
.PHONY : quick-lint-js-licenses/fast

#=============================================================================
# Target rules for targets named quick-lint-js-boost-json

# Build rule for target.
quick-lint-js-boost-json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-boost-json
.PHONY : quick-lint-js-boost-json

# fast build rule for target.
quick-lint-js-boost-json/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/quick-lint-js-boost-json.dir/build.make src/CMakeFiles/quick-lint-js-boost-json.dir/build
.PHONY : quick-lint-js-boost-json/fast

#=============================================================================
# Target rules for targets named quick-lint-js-test-lib

# Build rule for target.
quick-lint-js-test-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-test-lib
.PHONY : quick-lint-js-test-lib

# fast build rule for target.
quick-lint-js-test-lib/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/quick-lint-js-test-lib.dir/build.make test/CMakeFiles/quick-lint-js-test-lib.dir/build
.PHONY : quick-lint-js-test-lib/fast

#=============================================================================
# Target rules for targets named quick-lint-js-test

# Build rule for target.
quick-lint-js-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-test
.PHONY : quick-lint-js-test

# fast build rule for target.
quick-lint-js-test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/quick-lint-js-test.dir/build.make test/CMakeFiles/quick-lint-js-test.dir/build
.PHONY : quick-lint-js-test/fast

#=============================================================================
# Target rules for targets named quick-lint-js-test-cli

# Build rule for target.
quick-lint-js-test-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick-lint-js-test-cli
.PHONY : quick-lint-js-test-cli

# fast build rule for target.
quick-lint-js-test-cli/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/quick-lint-js-test-cli.dir/build.make test/CMakeFiles/quick-lint-js-test-cli.dir/build
.PHONY : quick-lint-js-test-cli/fast

vendor/boost-json.o: vendor/boost-json.cpp.o
.PHONY : vendor/boost-json.o

# target to build an object file
vendor/boost-json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_json.dir/build.make CMakeFiles/boost_json.dir/vendor/boost-json.cpp.o
.PHONY : vendor/boost-json.cpp.o

vendor/boost-json.i: vendor/boost-json.cpp.i
.PHONY : vendor/boost-json.i

# target to preprocess a source file
vendor/boost-json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_json.dir/build.make CMakeFiles/boost_json.dir/vendor/boost-json.cpp.i
.PHONY : vendor/boost-json.cpp.i

vendor/boost-json.s: vendor/boost-json.cpp.s
.PHONY : vendor/boost-json.s

# target to generate assembly for a file
vendor/boost-json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_json.dir/build.make CMakeFiles/boost_json.dir/vendor/boost-json.cpp.s
.PHONY : vendor/boost-json.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... quick-lint-js-build-tools"
	@echo "... quick-lint-js-licenses"
	@echo "... quick-lint-js-vscode-node-licenses"
	@echo "... boost_json"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... quick-lint-js"
	@echo "... quick-lint-js-analyze-trace"
	@echo "... quick-lint-js-boost-json"
	@echo "... quick-lint-js-fuzz-configuration-json"
	@echo "... quick-lint-js-fuzz-lex"
	@echo "... quick-lint-js-fuzz-lsp-message-parser"
	@echo "... quick-lint-js-fuzz-lsp-server"
	@echo "... quick-lint-js-fuzz-options"
	@echo "... quick-lint-js-fuzz-parse"
	@echo "... quick-lint-js-fuzz-parse-lint"
	@echo "... quick-lint-js-fuzz-utf-8-decode-encode"
	@echo "... quick-lint-js-fuzz-utf-8-lsp"
	@echo "... quick-lint-js-generate-lex-keyword"
	@echo "... quick-lint-js-lib"
	@echo "... quick-lint-js-lib-debug"
	@echo "... quick-lint-js-test"
	@echo "... quick-lint-js-test-cli"
	@echo "... quick-lint-js-test-lib"
	@echo "... quick-lint-js-test-typescript"
	@echo "... quick-lint-js-tool-lib"
	@echo "... quick-lint-js-typescript-test-lib"
	@echo "... quick-lint-js-vscode-node"
	@echo "... simdjson"
	@echo "... vendor/boost-json.o"
	@echo "... vendor/boost-json.i"
	@echo "... vendor/boost-json.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

